env: "local"
http-server:
  address: "localhost:8082"
  timeout: 4s
  iddle-timeout: 120s
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  name: "seams_db"
  sslmode: "disable"
  migrations-path: "./migrations"

  